kind: ConfigMap
apiVersion: v1
metadata:
  name: scheduler-config
  namespace: scheduler-plugins
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: scheduler-plugins
    meta.helm.sh/release-namespace: default
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    # Compose all plugins in one profile
    - schedulerName: scheduler-plugins-scheduler
      plugins:
      # Ensure only the first queueSort plugin is rendered.
        queueSort:
          enabled:
          - name: Coscheduling
          disabled:
          - name: "*"
        filter:
          enabled:
           - name: NodeResourceTopologyMatch
        permit:
          enabled:
           - name: Coscheduling
        postBind:
          enabled:
           - name: Coscheduling
        postFilter:
          enabled:
           - name: Coscheduling
           - name: CapacityScheduling
        preFilter:
          enabled:
           - name: Coscheduling
           - name: CapacityScheduling
        reserve:
          enabled:
           - name: Coscheduling
           - name: CapacityScheduling
        score:
          enabled:
           - name: NodeResourceTopologyMatch
           - name: NodeResourcesAllocatable
           - name: NodeResourcesFit
             weight: 10
      pluginConfig:
        - args:
            scoringStrategy:
              resources:
              - name: cpu
                weight: 1
              - name: nvidia.com/gpu
                weight: 1
              requestedToCapacityRatio:
                shape:
                - utilization: 0
                  score: 0 
                - utilization: 100
                  score: 10
              type: RequestedToCapacityRatio
          name: NodeResourcesFit